FROM python
RUN pip install flask gunicorn
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
WORKDIR /home/myapp
ENV PYTHONPATH /home/myapp
EXPOSE 8888
CMD gunicorn --bind 0.0.0.0:8888 sample_app:sample
